# -*- coding: utf-8 -*-
"""Scatterplot_with_matplotlib_seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YDLqOYoA7cCMVrqlr0UrZVEarq-3OE5U
"""

# Scatter plot: The values of 2 variables are plotted as points on a 2-dimensional grid.
# Additionally, you can also use a third variableto determine the size or color of the points.
import matplotlib.pyplot as plt
import seaborn as srn
# Load data into a pandas dataframe
iris_data=srn.load_dataset('iris')
# iris dataset already load in seaborn library
print(iris_data)

iris_data.species.unique()

# Let's try to visulize the relationship between sepal_length and sepal_width.First we create line chart using plt.plot the output is not very informative
# As there are too many combination of the two properties within the dataset, and there doesn't seem to be relationship between them.
srn.set_style('darkgrid')
plt.plot(iris_data.sepal_length,iris_data.sepal_width)

# We can use a scatter plot to visulize how sepal_length and sepal_width varyusing the scatterplot function from seaborn
srn.scatterplot((iris_data.sepal_length,iris_data.sepal_width))

# We can use a scatter plot to visulize how sepal_length and sepal_width varyusing the scatterplot function from seaborn
srn.scatterplot(x=iris_data.sepal_length,y=iris_data.sepal_width)

from matplotlib import figure
# Adding hues: How points in the above plot seem to form distinct cluster with some outliers.
# We can color the dots using the flower species as a hue. We can alsomake the points larger using the s argument.
srn.scatterplot(x=iris_data.sepal_length,y=iris_data.sepal_width,hue=iris_data.species,s=100)

# Customizing seaborn figures: Seaborn uses matplotlib plotting functions internally, We can use like plt.figure and plt.title
plt.figure(figsize=(10,5))
plt.title("Spetal Dimensions")
srn.scatterplot(x=iris_data.sepal_length,y=iris_data.sepal_width,hue=iris_data.species,s=100)

# Plotting using pandas data frame: Seaborn has in-built support for pandas data frames.
# Instead of passing each column as a series, you can also pass column names and use the data argument to pass the data frame.
plt.figure(figsize=(10,5))
plt.title("Petal Dimensions")
srn.scatterplot(x=iris_data.petal_length,y=iris_data.petal_width,hue=iris_data.species,s=100)

# Relation between three dataset
plt.figure(figsize=(10,6))
#plt.title("Iris Data Dimensions")
srn.scatterplot(x=iris_data.sepal_length,y=iris_data.sepal_width,c=iris_data.petal_length,hue=iris_data.species,s=100)